import sys
from distutils.core import setup

import py2exe
base = None
if sys.platform == "win32":
    base = "Win32GUI"
setup(
    name='TSVtoCSV',
    version='0.1',
    packages=['venv.lib.python3.5.site-packages.pip', 'venv.lib.python3.5.site-packages.pip.req',
              'venv.lib.python3.5.site-packages.pip.vcs', 'venv.lib.python3.5.site-packages.pip.utils',
              'venv.lib.python3.5.site-packages.pip.compat', 'venv.lib.python3.5.site-packages.pip.models',
              'venv.lib.python3.5.site-packages.pip._vendor', 'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations',
              'venv.lib.python3.5.site-packages.PyQt5', 'venv.lib.python3.5.site-packages.PyQt5.uic',
              'venv.lib.python3.5.site-packages.PyQt5.uic.Loader', 'venv.lib.python3.5.site-packages.PyQt5.uic.port_v2',
              'venv.lib.python3.5.site-packages.PyQt5.uic.port_v3',
              'venv.lib.python3.5.site-packages.PyQt5.uic.Compiler', 'venv.lib.python3.5.site-packages.py2exe',
              'venv.lib.python3.5.site-packages.setuptools', 'venv.lib.python3.5.site-packages.setuptools.extern',
              'venv.lib.python3.5.site-packages.setuptools.command', 'venv.lib.python3.5.site-packages.pkg_resources',
              'venv.lib.python3.5.site-packages.pkg_resources.extern',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging',
              'venv.lib64.python3.5.site-packages.pip', 'venv.lib64.python3.5.site-packages.pip.req',
              'venv.lib64.python3.5.site-packages.pip.vcs', 'venv.lib64.python3.5.site-packages.pip.utils',
              'venv.lib64.python3.5.site-packages.pip.compat', 'venv.lib64.python3.5.site-packages.pip.models',
              'venv.lib64.python3.5.site-packages.pip._vendor',
              'venv.lib64.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib64.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib64.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib64.python3.5.site-packages.pip._vendor.progress',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib64.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib64.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib64.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib64.python3.5.site-packages.pip.commands', 'venv.lib64.python3.5.site-packages.pip.operations',
              'venv.lib64.python3.5.site-packages.PyQt5', 'venv.lib64.python3.5.site-packages.PyQt5.uic',
              'venv.lib64.python3.5.site-packages.PyQt5.uic.Loader',
              'venv.lib64.python3.5.site-packages.PyQt5.uic.port_v2',
              'venv.lib64.python3.5.site-packages.PyQt5.uic.port_v3',
              'venv.lib64.python3.5.site-packages.PyQt5.uic.Compiler', 'venv.lib64.python3.5.site-packages.setuptools',
              'venv.lib64.python3.5.site-packages.setuptools.extern',
              'venv.lib64.python3.5.site-packages.setuptools.command',
              'venv.lib64.python3.5.site-packages.pkg_resources',
              'venv.lib64.python3.5.site-packages.pkg_resources.extern',
              'venv.lib64.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib64.python3.5.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='MIT',
    author='Joshua Menke',
    author_email='j.menke@me.com',
    description='',
    console=['main.py']
)
